version: '3.1'

services:
  mongo:
    image: mongo
    container_name: pm_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pepe
      MONGO_INITDB_ROOT_PASSWORD: qw7as4zx1
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data: