version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pepeolivert}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qw7as4zx1}
      POSTGRES_DB: ${POSTGRES_DB:-pmi}
      PGDATA: /data/postgres
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres_net
  
  

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_vol:
  
